service: node-sls

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
