service: node-sls

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  createContent:
    handler: content.contentAdded
    events:
      - http:
          path: content
          method: put 
  contentList:
    handler: content.contentDisplay
    events:
      - http:
          path: content
          method: get                     
